# Generated by Django 4.0 on 2022-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='team_color',
            field=models.CharField(default='rgba(240, 116, 137, 1)', max_length=25, null=True, verbose_name='COLOR'),
        ),
    ]
